// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwnQj_7B2-cp7qz4wVLOW92AGMXBAuA9Q',
    appId: '1:402539835398:web:cb63870c08ab446b751387',
    messagingSenderId: '402539835398',
    projectId: 'geo-aid-hub',
    authDomain: 'geo-aid-hub.firebaseapp.com',
    storageBucket: 'geo-aid-hub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYKUiuogLtWYZJiI13WlhFy7QMevie5mQ',
    appId: '1:402539835398:android:291b105568fc5db5751387',
    messagingSenderId: '402539835398',
    projectId: 'geo-aid-hub',
    storageBucket: 'geo-aid-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA01-ZRu4wrXcnXpTnXfiL-AGBQTxSLwyc',
    appId: '1:402539835398:ios:c050d2ef4eb8dbdd751387',
    messagingSenderId: '402539835398',
    projectId: 'geo-aid-hub',
    storageBucket: 'geo-aid-hub.firebasestorage.app',
    iosBundleId: 'com.example.sosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA01-ZRu4wrXcnXpTnXfiL-AGBQTxSLwyc',
    appId: '1:402539835398:ios:c050d2ef4eb8dbdd751387',
    messagingSenderId: '402539835398',
    projectId: 'geo-aid-hub',
    storageBucket: 'geo-aid-hub.firebasestorage.app',
    iosBundleId: 'com.example.sosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwnQj_7B2-cp7qz4wVLOW92AGMXBAuA9Q',
    appId: '1:402539835398:web:703770655c7cc86a751387',
    messagingSenderId: '402539835398',
    projectId: 'geo-aid-hub',
    authDomain: 'geo-aid-hub.firebaseapp.com',
    storageBucket: 'geo-aid-hub.firebasestorage.app',
  );
}
